### ISSUE TITLE
app crash in startActivityForResult on API 21

### ISSUE THREAD

**Issue by fparrav** [Omega-R/OmegaIntentBuilder#71]
When I run an activity to select image or capture photos in API 21 the application crashes and the following message appears in the logcat :

android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?`

**Comment by RomanTcv** [comment]
Hi, kaosrq. Thank you for your feedback. We fixed this bug in new version (1.0.9). 
Good luck.

**Comment by fparrav** [comment]
Thanks for the quick response ... this solved my problem!
